/**
 * Seed role definitions — the default Role/RolePermissionMap rows created by
 * `prisma/seed.js`. This is a starting point, not a hardcoded ceiling: once
 * seeded, roles/permissions become ordinary database rows manageable via
 * backend/src/services/rbac.service.js (and, later, an Admin Panel UI) with
 * no code change required to rename, merge, or re-scope them.
 *
 * Plant scope is deliberately NOT baked into the role — it lives on the
 * `User.plants` column instead (see seedLegacyAccounts in prisma/seed.js).
 * That's why there's one "Production Manager" role, not six near-duplicates.
 */
import { PERMISSION_KEYS } from './permissions.catalog.js'

const all = (...prefixes) => PERMISSION_KEYS.filter((k) => prefixes.some((p) => k.startsWith(`${p}.`)))
const viewOnly = (keys) => keys.filter((k) => k.endsWith('.view') || k === 'admin.panel.access')

const inventoryAll = all('inventory')
const plantModules = ['plant-microbial', 'plant-nano', 'plant-botanical', 'plant-liquid', 'plant-powder', 'plant-granules']
const plantAll = all(...plantModules)
const productionAll = all('production', 'planning', 'microbial')
const salesAll = all('sales')

export const ROLE_SEEDS = [
  {
    name: 'Super Admin',
    description: 'Full, unrestricted access to every module and action.',
    isSystem: true,
    permissions: PERMISSION_KEYS,
  },
  {
    name: 'Read-Only Admin',
    description: 'Can view every module across the app; cannot create, update, delete, or approve anything.',
    isSystem: true,
    permissions: viewOnly(PERMISSION_KEYS),
  },
  {
    name: 'Gate Manager',
    description: 'Full control of Gate Inward/Outward; can see overall stock levels.',
    isSystem: true,
    permissions: [...all('gate'), 'inventory.stock.view'],
  },
  {
    name: 'Gate Viewer',
    description: 'Read-only access to Gate Inward/Outward records.',
    isSystem: true,
    permissions: ['gate.inward.view', 'gate.outward.view'],
  },
  {
    name: 'Store Manager',
    description: 'Full control of Store/Inventory operations, including approvals; read access to relevant masters. ' +
      'Also creates/approves the Gate Inward backing entry generated by manual Print Master submissions.',
    isSystem: true,
    permissions: [
      ...inventoryAll,
      'gate.inward.view', 'gate.inward.create', 'gate.inward.update', 'gate.outward.view',
      'masters.rm.view', 'masters.product.view',
      // Notification delivery log — previously authorize(['admin','store']).
      'sales.notification.view',
    ],
  },
  {
    name: 'Store Viewer',
    description: 'Read-only access to Store/Inventory records — no create, adjust, or approve.',
    isSystem: true,
    permissions: viewOnly(inventoryAll),
  },
  {
    name: 'Production Manager',
    description: 'Full control of Production, Planning, and Microbial SFG operations for their assigned plant(s).',
    isSystem: true,
    permissions: [
      ...productionAll,
      // Recipe/BOM edits stay admin-only (matches the pre-migration
      // authorize(['admin']) gate on those two routes) — Production Manager
      // only gets read access here, same as before.
      'masters.recipe.view', 'masters.product.view', 'masters.equipment.view',
      // Microbe Master CRUD, by contrast, WAS production-operation-gated
      // before this migration — full access preserved here.
      'masters.microbe.view', 'masters.microbe.create', 'masters.microbe.update', 'masters.microbe.delete',
      // This one role is shared by all 6 plant-scoped accounts (Microbial,
      // Nano, Botanical, ...) — it carries full capability across every
      // plant module; which plant(s) a given login can actually reach is
      // narrowed separately by that user's own `plants[]`.
      ...plantAll,
    ],
  },
  {
    name: 'Production Viewer',
    description: 'Read-only access to Production, Planning, and Microbial SFG records for their assigned plant(s).',
    isSystem: true,
    permissions: viewOnly([
      ...productionAll,
      'masters.recipe.view', 'masters.product.view', 'masters.equipment.view', 'masters.microbe.view',
      ...plantAll,
    ]),
  },
  // ── Optional / forward-looking — unused by any legacy account, assignable later ──
  {
    name: 'Sales Manager',
    description: 'Full control of Sales Orders, Customer Profiles, BOM Sends, and Tracker.',
    isSystem: false,
    permissions: salesAll,
  },
  {
    name: 'Sales Executive',
    description: 'Can view and create/update Sales Orders and Customer Profiles; cannot cancel, dispatch, or delete.',
    isSystem: false,
    permissions: [
      'sales.order.view', 'sales.order.create', 'sales.order.update',
      'sales.tracker.view',
      'sales.customer-profile.view', 'sales.customer-profile.create', 'sales.customer-profile.update',
    ],
  },
  {
    name: 'Planning Manager',
    description: 'Full control of the Planning module.',
    isSystem: false,
    permissions: all('planning'),
  },
]

/**
 * Snapshot of the 18 accounts that used to live in backend/access.js (now
 * deleted — retired the moment login moved to the database). Kept here,
 * not imported from that file, precisely so this seed stays valid and
 * re-runnable forever, independent of that file's lifetime. Each account's
 * original plaintext password is hashed at seed time (see prisma/seed.js);
 * this is a one-time credential migration, not an ongoing dependency.
 */
export const LEGACY_ACCOUNTS = [
  { email: 'gate@agrilife.com', password: 'gate@745', fullName: 'gate', role: 'Gate Manager', plant: null },
  { email: 'gateemployee@agrilife.com', password: 'gate@7405emp', fullName: 'gateemployee', role: 'Gate Viewer', plant: null },
  { email: 'store@agrilife.com', password: 'store@789', fullName: 'store', role: 'Store Manager', plant: null },
  { email: 'storeemployee@agrilife.com', password: 'store@7890emp', fullName: 'storeemployee', role: 'Store Viewer', plant: null },
  { email: 'admin@agrilife.com', password: 'admin@2005', fullName: 'admin', role: 'Super Admin', plant: null },
  { email: 'adminemployee@agrilife.com', password: 'admin@2005emp', fullName: 'adminemployee', role: 'Read-Only Admin', plant: null },
  { email: 'microbial@agrilife.com', password: 'microbial@123', fullName: 'microbial', role: 'Production Manager', plant: 'Microbial' },
  { email: 'microbialemployee@agrilife.com', password: 'microbial@emp123', fullName: 'microbialemployee', role: 'Production Viewer', plant: 'Microbial' },
  { email: 'nano@agrilife.com', password: 'nano@123', fullName: 'nano', role: 'Production Manager', plant: 'Nano' },
  { email: 'nanoemployee@agrilife.com', password: 'nano@emp123', fullName: 'nanoemployee', role: 'Production Viewer', plant: 'Nano' },
  { email: 'botanical@agrilife.com', password: 'botanical@123', fullName: 'botanical', role: 'Production Manager', plant: 'Botanical' },
  { email: 'botanicalemployee@agrilife.com', password: 'botanical@emp123', fullName: 'botanicalemployee', role: 'Production Viewer', plant: 'Botanical' },
  { email: 'liquid@agrilife.com', password: 'liquid@123', fullName: 'liquid', role: 'Production Manager', plant: 'Liquid' },
  { email: 'liquidemployee@agrilife.com', password: 'liquid@emp123', fullName: 'liquidemployee', role: 'Production Viewer', plant: 'Liquid' },
  { email: 'powder@agrilife.com', password: 'powder@123', fullName: 'powder', role: 'Production Manager', plant: 'Powder' },
  { email: 'powderemployee@agrilife.com', password: 'powder@emp123', fullName: 'powderemployee', role: 'Production Viewer', plant: 'Powder' },
  { email: 'granules@agrilife.com', password: 'granules@123', fullName: 'granules', role: 'Production Manager', plant: 'Granules' },
  { email: 'granulesemployee@agrilife.com', password: 'granules@emp123', fullName: 'granulesemployee', role: 'Production Viewer', plant: 'Granules' },
]
